import { content } from "./content";
import { svg } from "./img";
import { Markdown } from "@/types/markdown";

export const markdown: Markdown[] = [
  {
    name: "Angular",
    content: content.angular,
    img: svg.angular,
    link: "angular",
  },
  {
    name: "Bash",
    content: content.bash,
    img: svg.bash,
    link: "bash",
  },
  {
    name: "CSS",
    content: content.css,
    img: svg.css,
    link: "css",
  },
  {
    name: "Docker",
    content: content.docker,
    img: svg.docker,
    link: "docker",
  },
  {
    name: "Flask",
    content: content.flask,
    img: svg.flask,
    link: "flask",
    canInvert: true,
  },
  {
    name: "Git",
    content: content.git,
    img: svg.git,
    link: "git",
  },
  {
    name: "GraphQL",
    content: content.graphQL,
    img: svg.graphQL,
    link: "graphql",
  },
  {
    name: "HTML",
    content: content.html,
    img: svg.html,
    link: "html",
  },
  {
    name: "Javascript",
    content: content.javascript,
    img: svg.javascript,
    link: "javascript",
  },
  {
    name: "LaTeX",
    content: content.latex,
    img: svg.latex,
    link: "latex",
    canInvert: true,
  },
  {
    name: "Mojo",
    content: content.mojo,
    img: svg.mojo,
    link: "mojo",
  },
  {
    name: "MongoDB",
    content: content.mongoDB,
    img: svg.mongoDB,
    link: "mongodb",
  },
  {
    name: "NextJS",
    content: content.nextJS,
    img: svg.nextJS,
    link: "nextjs",
    canInvert: true,
  },
  {
    name: "Prisma",
    content: content.prisma,
    img: svg.prisma,
    link: "prisma",
    canInvert: true,
  },
  {
    name: "Python",
    content: content.python,
    img: svg.python,
    link: "python",
  },
  {
    name: "React Native",
    content: content.reactNative,
    img: svg.reactNative,
    link: "react-native",
    canInvert: true,
  },
  {
    name: "React",
    content: content.react,
    img: svg.react,
    link: "react",
  },
  {
    name: "Redis",
    content: content.redis,
    img: svg.redis,
    link: "redis",
  },
  {
    name: "Rust",
    content: content.rust,
    img: svg.rust,
    link: "rust",
  },
  {
    name: "SCSS",
    content: content.scss,
    img: svg.scss,
    link: "scss",
  },
  {
    name: "SQL",
    content: content.sql,
    img: svg.sql,
    link: "sql",
  },
  {
    name: "Tailwind CSS",
    content: content.tailwindCSS,
    img: svg.tailwindCSS,
    link: "tailwind-css",
  },
  {
    name: "Tanstack Query",
    content: content.tanstackQuery,
    img: svg.tanstackQuery,
    link: "tanstack-query",
  },
  {
    name: "Tauri",
    content: content.tauri,
    img: svg.tauri,
    link: "tauri",
  },
  {
    name: "Typescript",
    content: content.typescript,
    img: svg.typescript,
    link: "typescript",
  },
  {
    name: "Zod",
    content: content.zod,
    img: svg.zod,
    link: "zod",
  },
];
