export const img = {
  angular: require("../assets/img/angular.png"),
  bash: require("../assets/img/bash.png"),
  css: require("../assets/img/css.png"),
  docker: require("../assets/img/docker.png"),
  flask: require("../assets/img/flask.png"),
  git: require("../assets/img/git.png"),
  graphQL: require("../assets/img/graphQL.png"),
  html: require("../assets/img/html.png"),
  javascript: require("../assets/img/javascript.png"),
  latex: require("../assets/img/latex.png"),
  mojo: require("../assets/img/mojo.png"),
  mongoDB: require("../assets/img/mongoDB.png"),
  nextJS: require("../assets/img/nextJS.png"),
  prisma: require("../assets/img/prisma.png"),
  python: require("../assets/img/python.png"),
  reactNative: require("../assets/img/expo.png"),
  react: require("../assets/img/react.png"),
  redis: require("../assets/img/redis.png"),
  rust: require("../assets/img/rust.png"),
  scss: require("../assets/img/scss.png"),
  sql: require("../assets/img/sql.png"),
  tailwindCSS: require("../assets/img/tailwindCSS.png"),
  tanstackQuery: require("../assets/img/tanstackQuery.png"),
  tauri: require("../assets/img/tauri.png"),
  typescript: require("../assets/img/typescript.png"),
  zod: require("../assets/img/zod.png"),
};
