import { content } from "./content";
import { img } from "./img";

import { Markdown, TechType } from "@/types/markdown";

export const techTypeHeadings: Record<TechType, string> = {
  [TechType.markUpLang]: "MarkUp Languages",
  [TechType.styleSheet]: "Stylesheet Languages and Frameworks",
  [TechType.programmingLang]: "Programming Languages",
  [TechType.devOps]: "Dev Ops",
  [TechType.webDev]: "Web Development Frameworks",
  [TechType.database]: "Databases and ORMs",
  [TechType.mobileDev]: "Mobile Development Frameworks",
  [TechType.desktopDev]: "Desktop Development Frameworks",
  [TechType.others]: "Other Technologies",
};

export const markdown: Markdown[] = [
  {
    name: "Angular",
    content: content.angular,
    img: img.angular,
    link: "angular",
    type: TechType.webDev,
  },
  {
    name: "Bash",
    content: content.bash,
    img: img.bash,
    link: "bash",
    type: TechType.programmingLang,
  },
  {
    name: "CSS",
    content: content.css,
    img: img.css,
    link: "css",
    type: TechType.styleSheet,
  },
  {
    name: "Docker",
    content: content.docker,
    img: img.docker,
    link: "docker",
    type: TechType.devOps,
  },
  {
    name: "Flask",
    content: content.flask,
    img: img.flask,
    link: "flask",
    canInvert: true,
    type: TechType.webDev,
  },
  {
    name: "Git",
    content: content.git,
    img: img.git,
    link: "git",
    type: TechType.devOps,
  },
  {
    name: "GraphQL",
    content: content.graphQL,
    img: img.graphQL,
    link: "graphql",
    type: TechType.others,
  },
  {
    name: "HTML",
    content: content.html,
    img: img.html,
    link: "html",
    type: TechType.markUpLang,
  },
  {
    name: "Javascript",
    content: content.javascript,
    img: img.javascript,
    link: "javascript",
    type: TechType.programmingLang,
  },
  {
    name: "LaTeX",
    content: content.latex,
    img: img.latex,
    link: "latex",
    canInvert: true,
    type: TechType.markUpLang,
  },
  {
    name: "Mojo",
    content: content.mojo,
    img: img.mojo,
    link: "mojo",
    type: TechType.programmingLang,
  },
  {
    name: "MongoDB",
    content: content.mongoDB,
    img: img.mongoDB,
    link: "mongodb",
    type: TechType.database,
  },
  {
    name: "NextJS",
    content: content.nextJS,
    img: img.nextJS,
    link: "nextjs",
    canInvert: true,
    type: TechType.webDev,
  },
  {
    name: "Prisma",
    content: content.prisma,
    img: img.prisma,
    link: "prisma",
    canInvert: true,
    type: TechType.database,
  },
  {
    name: "Python",
    content: content.python,
    img: img.python,
    link: "python",
    type: TechType.programmingLang,
  },
  {
    name: "React Native",
    content: content.reactNative,
    img: img.reactNative,
    link: "react-native",
    canInvert: true,
    type: TechType.mobileDev,
  },
  {
    name: "React",
    content: content.react,
    img: img.react,
    link: "react",
    type: TechType.webDev,
  },
  {
    name: "Redis",
    content: content.redis,
    img: img.redis,
    link: "redis",
    type: TechType.database,
  },
  {
    name: "Rust",
    content: content.rust,
    img: img.rust,
    link: "rust",
    type: TechType.programmingLang,
  },
  {
    name: "SCSS",
    content: content.scss,
    img: img.scss,
    link: "scss",
    type: TechType.styleSheet,
  },
  {
    name: "SQL",
    content: content.sql,
    img: img.sql,
    link: "sql",
    type: TechType.database,
  },
  {
    name: "Tailwind CSS",
    content: content.tailwindCSS,
    img: img.tailwindCSS,
    link: "tailwind-css",
    type: TechType.styleSheet,
  },
  {
    name: "Tanstack Query",
    content: content.tanstackQuery,
    img: img.tanstackQuery,
    link: "tanstack-query",
    type: TechType.others,
  },
  {
    name: "Tauri",
    content: content.tauri,
    img: img.tauri,
    link: "tauri",
    type: TechType.desktopDev,
  },
  {
    name: "Typescript",
    content: content.typescript,
    img: img.typescript,
    link: "typescript",
    type: TechType.programmingLang,
  },
  {
    name: "Zod",
    content: content.zod,
    img: img.zod,
    link: "zod",
    type: TechType.others,
  },
];
